apiVersion: v1
kind: ConfigMap
metadata:
  name: vulnerable-app-source
  namespace: demo1-compromised-dependency
  labels:
    app: vulnerable-app
    demo: compromised-dependency
data:
  package.json: |
    {
      "name": "vulnerable-app",
      "version": "1.0.0",
      "description": "Sample app with vulnerable dependency",
      "dependencies": {
        "log4js": "6.3.0",
        "express": "4.17.1"
      }
    }
  app.js: |
    const express = require('express');
    const log4js = require('log4js');
    const app = express();
    const port = 8080;

    // Configure log4js (vulnerable version)
    log4js.configure({
      appenders: { console: { type: 'console' } },
      categories: { default: { appenders: ['console'], level: 'info' } }
    });

    const logger = log4js.getLogger();

    app.get('/', (req, res) => {
      logger.info('Request received');
      res.json({ 
        message: 'Vulnerable App Running',
        version: '1.0.0',
        dependency: 'log4js@6.3.0 (VULNERABLE)'
      });
    });

    app.listen(port, () => {
      logger.info(`Vulnerable app listening on port ${port}`);
    });
  Dockerfile: |
    FROM node:16-alpine
    WORKDIR /app
    COPY package.json app.js ./
    RUN npm install
    EXPOSE 8080
    CMD ["node", "app.js"]

